<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <DefaultItemExcludes>$(DefaultItemExcludes);Tests\**</DefaultItemExcludes>
    <Version>0.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Tests\**" />
    <None Remove="Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="logo.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="logo.png" />
    <EmbeddedResource Include="icon.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Icons\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="RJCP.SerialPortStream" Version="3.0.4" />
  </ItemGroup>

</Project>