<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="logo.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="logo.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Svg" Version="3.4.7" />
    <PackageReference Include="RJCP.SerialPortStream" Version="3.0.4" />
  </ItemGroup>

</Project>