<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
    <PackageReference Include="OpenCvSharp4.Extensions" Version="4.11.0.20250507" />
    <PackageReference Include="OpenCvSharp4.Windows" Version="4.11.0.20250507" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <!-- <ProjectReference Include="..\..\laser_gui_test.csproj" /> -->
    <Compile Include="..\..\Data\SvgImporter.cs" Link="Data\SvgImporter.cs" />
    <Compile Include="..\..\Data\LaserObject.cs" Link="Data\LaserObject.cs" />
    <Compile Include="..\..\Data\LaserGroup.cs" Link="Data\LaserGroup.cs" />
    <Compile Include="..\..\Data\ProjectState.cs" Link="Data\ProjectState.cs" />
    <Compile Include="..\..\Data\PathWarp.cs" Link="Data\PathWarp.cs" />
    <Compile Include="..\..\Data\AppConfiguration.cs" Link="Data\AppConfiguration.cs" />
    <Compile Include="..\..\Data\Layer.cs" Link="Data\Layer.cs" />
  </ItemGroup>

</Project>
