<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="grbl_burn_em">
      <HintPath>..\bin\Debug\net9.0-windows10.0.19041.0\grbl_burn_em.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
